### PR TITLE
fix(separator): fix stories for 9.1.4.10 criteria #1007

### LINKED ISSUE #63: [Separator]: WCAG react issues
## Problem
9.1.4.10 - Separator segab kaartide informatsiooni lugemist kriteeriumi tingimustel.

### PR DESCRIPTION
**Pull request by airikej**

### CODE REVIEW

File: libs/react-components/src/tedi/components/misc/separator/separator.tsx [hunk 1]
```diff
@@ -139,9 +142,15 @@ export const Separator = (props: SeparatorProps): JSX.Element => {
     { [styles['tedi-separator--is-stretched']]: isStretched },
     { [styles[`tedi-separator--spacing-${spacing}`.replace('.', '-')]]: spacing },
     { [styles[`tedi-separator--top-${topSpacing}`.replace('.', '-')]]: !spacing && topSpacing },
-    { [styles[`tedi-separator--bottom-${bottomSpacing}`.replace('.', '-')]]: !spacing && bottomSpacing }
+    { [styles[`tedi-separator--bottom-${bottomSpacing}`.replace('.', '-')]]: !spacing && bottomSpacing },
+    className
   );
 
+  const accessibilityProps =
```
Comment (mart-sessman) [inline libs/react-components/src/tedi/components/misc/separator/separator.tsx]: If element is hr then role: 'separator' is not needed.
It is only needed when element is not hr.
Aria hidden is not needed at all.

**Review by mart-sessman — CHANGES_REQUESTED** [review]

**Review by mart-sessman — APPROVED** [review]
